// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';
import RevealController from './reveal_controller';
application.register('reveal', RevealController);

import DarkModeController from './dark_mode_controller';
application.register('dark-mode', DarkModeController);

import HelloController from './hello_controller';
application.register('hello', HelloController);

import MarkdownPreviewerController from './markdown_previewer_controller';
application.register('markdown-previewer', MarkdownPreviewerController);

import Clipboard from './clipboard_controller';
application.register('clipboard', Clipboard);
