// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import ClipboardController from './clipboard_controller';
application.register('clipboard', ClipboardController);

import DarkModeController from './dark_mode_controller';
application.register('dark-mode', DarkModeController);

import MarkdownPreviewerController from './markdown_previewer_controller';
application.register('markdown-previewer', MarkdownPreviewerController);

import RevealController from './reveal_controller';
application.register('reveal', RevealController);

import AutocompleteController from './autocomplete_controller';
application.register('autocomplete', AutocompleteController);
