require:
  - rubocop
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/markdown_helper.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
